import { z } from "zod";
import {
  createClient,
  createEventClient,
  defineContract,
  defineEvent,
} from "../contracts/core";
import type {
  ImageGenerationOperationOutcome,
  ImageGenerationResultView,
  ImageThemeMode,
} from "../../image_generation/state";

export type { ImageGenerationResultView, ImageThemeMode };
export type { ImageGenerationOperationOutcome };

export const ImageThemeModeSchema = z.enum([
  "plain",
  "3d-clay",
  "real-photography",
  "isometric-illustration",
]);

// Schema for the raw API response from the image generation service. This is
// main-only data validation; generated bytes never cross the IPC boundary.
export const ImageGenerationApiResponseSchema = z.object({
  created: z.number(),
  data: z.array(
    z.object({
      url: z.string().nullable().optional(),
      b64_json: z.string().nullable().optional(),
      revised_prompt: z.string().nullable().optional(),
    }),
  ),
});

export const ImageGenerationResultViewSchema = z
  .object({
    fileName: z.string(),
    appId: z.number(),
    appName: z.string(),
  })
  .strict();

export const ImageGenerationPresentationEventSchema = z.discriminatedUnion(
  "type",
  [
    z
      .object({
        type: z.literal("progress"),
        pendingCount: z.number().int().nonnegative(),
      })
      .strict(),
    z
      .object({
        type: z.literal("succeeded"),
        result: ImageGenerationResultViewSchema,
        pendingCount: z.number().int().nonnegative(),
      })
      .strict(),
    z
      .object({
        type: z.literal("failed"),
        message: z.string(),
        pendingCount: z.number().int().nonnegative(),
      })
      .strict(),
  ],
);
export type ImageGenerationPresentationEvent = z.infer<
  typeof ImageGenerationPresentationEventSchema
>;

const ImageGenerationOperationOutcomeObjectSchema = z.discriminatedUnion(
  "kind",
  [
    z
      .object({
        kind: z.literal("succeeded"),
        jobId: z.string(),
        result: ImageGenerationResultViewSchema,
      })
      .strict(),
    z
      .object({
        kind: z.literal("failed"),
        jobId: z.string(),
        message: z.string(),
        failureKind: z.enum(["provider", "unexpected"]),
      })
      .strict(),
    z.object({ kind: z.literal("cancelled"), jobId: z.string() }).strict(),
    z
      .object({
        kind: z.literal("disposed"),
        jobId: z.string(),
        cause: z.enum([
          "actor",
          "key",
          "machine",
          "host",
          "window-session",
          "app-deletion",
        ]),
      })
      .strict(),
    z
      .object({
        kind: z.literal("rejected"),
        jobId: z.string(),
        reason: z.enum([
          "already-cancelling",
          "already-terminal",
          "duplicate-job",
          "job-id-conflict",
          "operation-id-conflict",
          "job-not-found",
          "stale-operation",
        ]),
      })
      .strict(),
  ],
);

export const ImageGenerationOperationOutcomeSchema = z
  .custom<unknown>((value) => !(value instanceof Error), {
    message: "Error instances are not image-generation domain outcomes",
  })
  .pipe(
    ImageGenerationOperationOutcomeObjectSchema,
  ) satisfies z.ZodType<ImageGenerationOperationOutcome>;

export const imageGenerationContracts = {
  waitForOperation: defineContract({
    channel: "image-generation:wait-for-operation",
    input: z.object({ requestId: z.string().min(1) }).strict(),
    output: ImageGenerationOperationOutcomeSchema,
  }),
} as const;

type MutuallyAssignable<Left, Right> = [Left] extends [Right]
  ? [Right] extends [Left]
    ? true
    : false
  : false;
type AssertTrue<Value extends true> = Value;

const imageGenerationSchemaTypeAssertions: [
  AssertTrue<
    MutuallyAssignable<
      z.infer<typeof ImageGenerationResultViewSchema>,
      ImageGenerationResultView
    >
  >,
  AssertTrue<
    MutuallyAssignable<z.infer<typeof ImageThemeModeSchema>, ImageThemeMode>
  >,
  AssertTrue<
    MutuallyAssignable<
      z.infer<typeof ImageGenerationOperationOutcomeSchema>,
      ImageGenerationOperationOutcome
    >
  >,
] = [true, true, true];
void imageGenerationSchemaTypeAssertions;

export const imageGenerationEvents = {
  presentation: defineEvent({
    channel: "image-generation:presentation",
    payload: ImageGenerationPresentationEventSchema,
  }),
} as const;

export const imageGenerationEventClient = createEventClient(
  imageGenerationEvents,
);
export const imageGenerationClient = createClient(imageGenerationContracts);
