import { z } from "zod";
import { createEventClient, defineEvent } from "../contracts/core";
import type {
  ImageGenerationResultView,
  ImageThemeMode,
} from "../../image_generation/state";

export type { ImageGenerationResultView, ImageThemeMode };

export const ImageThemeModeSchema = z.enum([
  "plain",
  "3d-clay",
  "real-photography",
  "isometric-illustration",
]);

// Schema for the raw API response from the image generation service. This is
// main-only data validation; generated bytes never cross the IPC boundary.
export const ImageGenerationApiResponseSchema = z.object({
  created: z.number(),
  data: z.array(
    z.object({
      url: z.string().nullable().optional(),
      b64_json: z.string().nullable().optional(),
      revised_prompt: z.string().nullable().optional(),
    }),
  ),
});

export const ImageGenerationResultViewSchema = z
  .object({
    fileName: z.string(),
    appId: z.number(),
    appName: z.string(),
  })
  .strict();

export const ImageGenerationPresentationEventSchema = z.discriminatedUnion(
  "type",
  [
    z
      .object({
        type: z.literal("progress"),
        pendingCount: z.number().int().nonnegative(),
      })
      .strict(),
    z
      .object({
        type: z.literal("succeeded"),
        result: ImageGenerationResultViewSchema,
        pendingCount: z.number().int().nonnegative(),
      })
      .strict(),
    z
      .object({
        type: z.literal("failed"),
        message: z.string(),
        pendingCount: z.number().int().nonnegative(),
      })
      .strict(),
  ],
);
export type ImageGenerationPresentationEvent = z.infer<
  typeof ImageGenerationPresentationEventSchema
>;

type MutuallyAssignable<Left, Right> = [Left] extends [Right]
  ? [Right] extends [Left]
    ? true
    : false
  : false;
type AssertTrue<Value extends true> = Value;

const imageGenerationSchemaTypeAssertions: [
  AssertTrue<
    MutuallyAssignable<
      z.infer<typeof ImageGenerationResultViewSchema>,
      ImageGenerationResultView
    >
  >,
  AssertTrue<
    MutuallyAssignable<z.infer<typeof ImageThemeModeSchema>, ImageThemeMode>
  >,
] = [true, true];
void imageGenerationSchemaTypeAssertions;

export const imageGenerationEvents = {
  presentation: defineEvent({
    channel: "image-generation:presentation",
    payload: ImageGenerationPresentationEventSchema,
  }),
} as const;

export const imageGenerationEventClient = createEventClient(
  imageGenerationEvents,
);
