# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: biome-lint
        name: Run Biome lint
        description: Run biome lint
        entry: sh -c 'yarn biome lint src --write --unsafe'
        files: \.(ts)$
        language: system
        pass_filenames: false
