site_name: Dyad Docs
site_url: https://docs.dyad.sh
repo_url: https://github.com/dyad-sh/dyad
strict: true
nav:
  - index.md
  - Getting Started:
      - getting-started/index.md
      - getting-started/quickstart.md
  - Features:
      - features/index.md
      - features/models.md
      - features/code-references.md
      - features/code-editing.md
      - features/indexing.md
      - features/workspace.md
      - features/agents.md
  - Extensions:
      - extensions/index.md
      - extensions/build-an-agent.md
      - extensions/build-a-tool.md
      - extensions/api.md
      - FAQ: extensions/faq.md
  - Reference:
      - cli.md
  - Contributing:
      - Development: internal/development.md
      - Publishing: internal/publishing.md
      - Packaging: internal/packaging.md
      - Sandpack: internal/sandpack.md
theme:
  name: material
  # custom_dir: docs/theme
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Geist Sans

  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: dyad-light
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: dyad-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.copy
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search.highlight

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - sane_lists
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.details

plugins:
  - blog
  - search
  - mkdocstrings:
      default_handler: python

      handlers:
        python:
          paths: [packages/dyad_core/src]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            heading_level: 3
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_if_no_docstring: true
            show_signature: true
            show_signature_annotations: true

            show_root_heading: true
            show_root_full_path: false
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
