export const distributedDefinitionInventory = [
  "app_run/definition.ts::appRunDefinition",
  "chat_stream/definition.ts::chatStreamDefinition",
  "ipc/services/github_ops_definition.ts::githubOpsDefinition",
  "ipc/services/image_generation_definition.ts::imageGenerationDefinition",
  "ipc/services/version_preview_definition.ts::versionPreviewDefinition",
  "plan_handoff/definition.ts::planHandoffDefinition",
] as const;

export const unsafeEscapeHatchInventory = {
  wideningCasts: [
    "app_run/definition.ts::appRunDefinition.remote.eventCodec",
    "chat_stream/definition.ts::chatStreamDefinition.remote.eventCodec",
    "ipc/services/github_ops_definition.ts::githubOpsDefinition.remote.eventCodec",
    "ipc/services/image_generation_definition.ts::imageGenerationDefinition.remote.eventCodec",
    "ipc/services/version_preview_definition.ts::versionPreviewDefinition.remote.eventCodec",
    "plan_handoff/definition.ts::planHandoffDefinition.remote.eventCodec",
  ],
  rawDispatchOrEnqueue: [
    "app_run/definition.ts::createCommandRunner::call(output.enqueue)",
    "chat_stream/remote_manager.ts::ChatStreamRemoteManager.dispatchCompatibilityCommand::call(this.actor().dispatch)",
    "chat_stream/remote_manager.ts::ChatStreamRemoteManager.dispatchQueueEvent::call(actor.dispatch)",
    "chat_stream/remote_manager.ts::ChatStreamRemoteManager.prepareAndDispatchSubmission::call(actor.dispatch)",
    "distributed_machines/actor_host.ts::HostedActor.activate::call(this.enqueue)",
    "distributed_machines/actor_host.ts::HostedActor.constructor.context.send::call(this.enqueue)",
    "distributed_machines/actor_host.ts::HostedActor.enqueueExpected::call(this.enqueue)",
    "distributed_machines/actor_host.ts::HostedActor.enqueueWithAdmission.ticket::call(this.dispatcher.enqueue)",
    "distributed_machines/actor_host.ts::HostedActor.send::call(this.enqueue)",
    "distributed_machines/ipc_connection.ts::IpcRemoteMachineConnection.dispatch::call(ipc.distributedMachine.dispatch)",
    "distributed_machines/react.ts::useDistributedMachine::access(actor.dispatch)",
    "distributed_machines/remote_client.ts::RemoteMachineClient.dispatch::call(this.connection.dispatch)",
    "distributed_machines/remote_client.ts::RemoteSnapshotStore.dispatch::call(this.client.dispatch)",
    "github_ops/useGithubOps.ts::useGithubOps.dispatch::access(remote.dispatch)",
    "github_ops/useGithubOps.ts::useGithubOps.dispatch::call(remote.dispatch)",
    "github_ops/useGithubOps.ts::useGithubOps.dispatchConflictResolutionCancelled::access(remote.dispatch)",
    "github_ops/useGithubOps.ts::useGithubOps.dispatchConflictResolutionCancelled::call(remote.dispatch)",
    "github_ops/useGithubOps.ts::useGithubOps.dispatchConflictResolutionStarted::access(remote.dispatch)",
    "github_ops/useGithubOps.ts::useGithubOps.dispatchConflictResolutionStarted::call(remote.dispatch)",
    "hooks/useVersionPreview.ts::useVersionPreview.dispatchNow::call(actor.dispatch)",
    "image_generation/hooks.ts::useImageGenerationRequestActor.cancellationActor.dispatchRequest::call(actor.dispatch)",
    "image_generation/hooks.ts::useImageGenerationRequestActor.completionAware.dispatchRequest::call(actor.dispatch)",
    "ipc/handlers/distributed_machine_handlers.ts::registerDistributedMachineHandlers::access(distributedMachineContracts.dispatch)",
    "ipc/handlers/distributed_machine_handlers.ts::registerDistributedMachineHandlers::call(transport.dispatch)",
    "ipc/services/image_generation_actor_service.ts::ImageGenerationActorService.finishAppDeletion::call(fence.actor.enqueue)",
    "ipc/services/image_generation_actor_service.ts::ImageGenerationActorService.prepareAppDeletion::call(fence.actor.enqueue)",
    "ipc/services/plan_handoff_service.ts::startPlanHandoffFromMain::call(actor.enqueue)",
    "plan_handoff/remote_manager.ts::PlanHandoffRemoteManager.accept::call(actor.dispatch)",
    "version_preview/VersionPreviewProvider.tsx::VersionPreviewProvider.subscribeSelected.inspect.action.onClick::call(actor.dispatch)",
  ],
  bespokeWaiters: ["hooks/useVersionPreview.ts::useVersionPreview.dispatchNow"],
  subscriptionRefCounts: [
    "chat_stream/remote_manager.ts::ChatStreamRemoteManager.subscriptions",
    "distributed_machines/actor_host.ts::HostedActor.reconcileRetention::uses(subscriberCount)",
    "distributed_machines/actor_host.ts::HostedActor.scheduleIdleEviction::uses(subscriberCount)",
    "distributed_machines/actor_host.ts::HostedActor.subscribe::uses(subscriberCount)",
    "distributed_machines/actor_host.ts::HostedActor.subscriberCount",
    "distributed_machines/remote_transport.ts::RemoteMachineTransport.beginPendingSubscription::uses(referencesPerWindow)",
    "distributed_machines/remote_transport.ts::RemoteMachineTransport.completeSubscription::uses(referencesPerWindow)",
    "distributed_machines/remote_transport.ts::RemoteMachineTransport.decrementWindowReferences::uses(referencesPerWindow)",
    "distributed_machines/remote_transport.ts::RemoteMachineTransport.dispose::uses(referencesPerWindow)",
    "distributed_machines/remote_transport.ts::RemoteMachineTransport.inspectSubscriptions::uses(totalReferences)",
    "distributed_machines/remote_transport.ts::RemoteMachineTransport.referencesPerWindow",
    "distributed_machines/remote_transport.ts::RemoteMachineTransport.subscriptions",
    "state_machines/snapshot_store.ts::SnapshotStore.subscriberCount",
    "user_input/read_model.ts::getUserInputReadModel.readModel.start.subscriptions",
  ],
  deletionResetFences: [
    "ipc/services/app_chat_creation_fence.ts::assertAppChatCreationOpen::uses(creationBlockCounts)",
    "ipc/services/app_chat_creation_fence.ts::beginAppChatMutation::uses(creationBlockCounts)",
    "ipc/services/app_chat_creation_fence.ts::creationBlockCounts",
    "ipc/services/chat_actor_deletion_fence.ts::admissionBlockCounts",
    "ipc/services/chat_actor_deletion_fence.ts::assertChatActorAdmissionOpen::uses(admissionBlockCounts)",
    "ipc/services/chat_actor_deletion_fence.ts::beginChatActorMutation::uses(admissionBlockCounts)",
    "ipc/services/github_ops_service.ts::GithubOpsService.assertAcceptingOperations::uses(deletionFences)",
    "ipc/services/github_ops_service.ts::GithubOpsService.assertAcceptingOperations::uses(resetFenceCount)",
    "ipc/services/github_ops_service.ts::GithubOpsService.beginAppDeletion::uses(deletionFences)",
    "ipc/services/github_ops_service.ts::GithubOpsService.beginReset::uses(resetFenceCount)",
    "ipc/services/github_ops_service.ts::GithubOpsService.deletionFences",
    "ipc/services/github_ops_service.ts::GithubOpsService.endAppDeletion::uses(deletionFences)",
    "ipc/services/github_ops_service.ts::GithubOpsService.endReset::uses(resetFenceCount)",
    "ipc/services/github_ops_service.ts::GithubOpsService.resetFenceCount",
    "ipc/services/image_generation_service.ts::ImageGenerationService.assertAcceptingGenerations::uses(deletionFences)",
    "ipc/services/image_generation_service.ts::ImageGenerationService.assertAcceptingGenerations::uses(resetFenceCount)",
    "ipc/services/image_generation_service.ts::ImageGenerationService.beginAppDeletion::uses(deletionFences)",
    "ipc/services/image_generation_service.ts::ImageGenerationService.beginReset::uses(resetFenceCount)",
    "ipc/services/image_generation_service.ts::ImageGenerationService.deletionFences",
    "ipc/services/image_generation_service.ts::ImageGenerationService.endAppDeletion::uses(deletionFences)",
    "ipc/services/image_generation_service.ts::ImageGenerationService.endReset::uses(resetFenceCount)",
    "ipc/services/image_generation_service.ts::ImageGenerationService.resetFenceCount",
    "ipc/services/version_preview_service.ts::VersionPreviewService.assertAcceptingOperations::uses(deletionFences)",
    "ipc/services/version_preview_service.ts::VersionPreviewService.assertAcceptingOperations::uses(resetFenceCount)",
    "ipc/services/version_preview_service.ts::VersionPreviewService.beginAppDeletion::uses(deletionFences)",
    "ipc/services/version_preview_service.ts::VersionPreviewService.beginReset::uses(resetFenceCount)",
    "ipc/services/version_preview_service.ts::VersionPreviewService.deletionFences",
    "ipc/services/version_preview_service.ts::VersionPreviewService.endAppDeletion::uses(deletionFences)",
    "ipc/services/version_preview_service.ts::VersionPreviewService.endReset::uses(resetFenceCount)",
    "ipc/services/version_preview_service.ts::VersionPreviewService.resetFenceCount",
  ],
  initiatorRoutingMaps: [
    "ipc/services/github_ops_presentation_service.ts::GithubOpsPresentationService.forget::uses(initiatorByOperationId)",
    "ipc/services/github_ops_presentation_service.ts::GithubOpsPresentationService.initiatorByOperationId",
    "ipc/services/github_ops_presentation_service.ts::GithubOpsPresentationService.recordInitiator::uses(initiatorByOperationId)",
    "ipc/services/github_ops_presentation_service.ts::GithubOpsPresentationService.showError::uses(initiatorByOperationId)",
    "ipc/services/image_generation_presentation_service.ts::ImageGenerationPresentationService.clear::uses(initiatorByJobId)",
    "ipc/services/image_generation_presentation_service.ts::ImageGenerationPresentationService.forgetApp::uses(initiatorByJobId)",
    "ipc/services/image_generation_presentation_service.ts::ImageGenerationPresentationService.initiatorByJobId",
    "ipc/services/image_generation_presentation_service.ts::ImageGenerationPresentationService.present::uses(initiatorByJobId)",
    "ipc/services/image_generation_presentation_service.ts::ImageGenerationPresentationService.recordInitiator::uses(initiatorByJobId)",
    "ipc/services/image_generation_presentation_service.ts::ImageGenerationPresentationService.routeForJob::uses(initiatorByJobId)",
    "ipc/services/version_preview_presentation_service.ts::VersionPreviewPresentationService.confirm::uses(initiatorByOperationId)",
    "ipc/services/version_preview_presentation_service.ts::VersionPreviewPresentationService.forget::uses(initiatorByOperationId)",
    "ipc/services/version_preview_presentation_service.ts::VersionPreviewPresentationService.initiatorByOperationId",
    "ipc/services/version_preview_presentation_service.ts::VersionPreviewPresentationService.originEndpointFor::uses(initiatorByOperationId)",
    "ipc/services/version_preview_presentation_service.ts::VersionPreviewPresentationService.recordInitiator::uses(initiatorByOperationId)",
    "ipc/services/version_preview_window_interest.ts::VersionPreviewWindowInterestService.acquire::uses(windowIdsByAppId)",
    "ipc/services/version_preview_window_interest.ts::VersionPreviewWindowInterestService.acquireIfUnowned::uses(windowIdsByAppId)",
    "ipc/services/version_preview_window_interest.ts::VersionPreviewWindowInterestService.clearAll::uses(windowIdsByAppId)",
    "ipc/services/version_preview_window_interest.ts::VersionPreviewWindowInterestService.clearApp::uses(windowIdsByAppId)",
    "ipc/services/version_preview_window_interest.ts::VersionPreviewWindowInterestService.inspect::uses(windowIdsByAppId)",
    "ipc/services/version_preview_window_interest.ts::VersionPreviewWindowInterestService.isLastOwner::uses(windowIdsByAppId)",
    "ipc/services/version_preview_window_interest.ts::VersionPreviewWindowInterestService.release::uses(windowIdsByAppId)",
    "ipc/services/version_preview_window_interest.ts::VersionPreviewWindowInterestService.removeWindow::uses(windowIdsByAppId)",
    "ipc/services/version_preview_window_interest.ts::VersionPreviewWindowInterestService.windowIdsByAppId",
  ],
} as const;

/**
 * Exact negative classification used to make raw dispatch discovery
 * re-export-safe. These calls are unrelated queues or domain facades, so they
 * stay out of the unsafe escape-hatch report while remaining pinned.
 */
export const nonRemoteDispatchOrEnqueueInventory = [
  "hooks/useRunApp.ts::useRebuildAppAfterPnpmInstall::call(manager.dispatch)",
  "ipc/services/app_runtime_service.ts::listenToProcess::call(output.enqueue)::direct",
  "ipc/services/app_runtime_service.ts::listenToProcess::call(output.enqueue)::when(isInputRequest)",
  "ipc/services/app_runtime_transport.ts::IpcAppRuntimeOutput.enqueue::call(appOutputInterests.enqueue)",
  "ipc/services/main_app_runtime_output.ts::MainAppRuntimeOutput.enqueue::call(appOutputInterests.enqueue)",
  "ipc/utils/debug_fetch.ts::debugFetch.start::call(controller.enqueue)",
  "ipc/utils/fallback_ai_model.ts::FallbackModel.createWrappedStream.start.processStream::call(controller.enqueue)",
  "state_machines/dispatcher.ts::TransactionalDispatcher.send::call(this.enqueue)",
  "supabase_admin/supabase_deploy_queue.ts::enqueueSupabaseDeploy::call(queue.enqueue)",
  "version_preview/window_interest_client.ts::VersionPreviewWindowInterestClient.acquire::call(this.enqueue)",
  "version_preview/window_interest_client.ts::VersionPreviewWindowInterestClient.release::call(this.enqueue)",
  "version_preview/window_interest_client.ts::VersionPreviewWindowInterestClient.restoreIfOrphaned::call(this.enqueue)",
  "window_infrastructure/main/high_volume_interests.ts::HighVolumeWindowInterests.terminalFlush::call(this.enqueue)",
] as const;

/**
 * Framework-owned request protocol boundaries. These are correlated or
 * explicitly admission-only paths, not unmigrated raw domain dispatch.
 */
export const completionAwareDispatchOrEnqueueInventory = [
  "distributed_machines/operation_registry.ts::admitOperationAndEnqueue::access(options.enqueue)",
  "app_run/definition.ts::appRunDefinition.remoteIntent.finalizeOperation.admission::access(controls.enqueue)",
  "distributed_machines/operation_registry.ts::admitOperationAndEnqueue::call(options.enqueue)",
  "distributed_machines/prepared_request.ts::prepareRequest.dispatchAttempt.attempt::call(options.dispatch)",
  "distributed_machines/request_actor.ts::createCompletionAwareActor::access(options.enqueue)",
  "distributed_machines/request_actor.ts::createRemoteRequestActor.request.dispatchRequest::call(options.actor.dispatch)",
  "distributed_machines/request_actor.ts::dispatchRemoteAdmissionOnly::call(actor.dispatch)",
  "distributed_machines/use_machine_mutation.ts::useMachineMutation.retry::call(current.request.retry.dispatch)",
  "ipc/services/app_run_actor_service.ts::AppRunActorService.dispatchAndWait.admission.enqueue::call(actor.enqueue)",
] as const;
