import path from "node:path";

export const PREVIEW_DNS_RELATIVE_PATH =
  "e2e-tests/fixtures/dyad/preview-dns.cjs";

/** Node/Playwright APIRequestContext does not use Chromium's localhost resolver. */
export function buildPreviewDnsSource(): string {
  return `// Generated by Dyad. Only active in a Dyad test runner.
const dns = require("node:dns");
const { syncBuiltinESMExports } = require("node:module");
let hostname;
try {
  const url = new URL(process.env.DYAD_TEST_BASE_URL);
  if (url.protocol === "http:" && url.port && !url.username && !url.password &&
      /^app-([1-9][0-9]*)\\.localhost$/.test(url.hostname) &&
      Number.isSafeInteger(Number(url.hostname.split(".")[0].slice(4)))) hostname = url.hostname;
} catch {}
if (hostname) {
  const lookup = dns.lookup;
  const lookupPromise = dns.promises.lookup;
  // Delegate even the local lookup to Node so family/all overloads and error
  // behavior stay identical. No URL rewriting: cookie/Host semantics survive.
  dns.lookup = function(host, ...args) {
    return lookup.call(this, host === hostname ? "127.0.0.1" : host, ...args);
  };
  dns.promises.lookup = function(host, ...args) {
    return lookupPromise.call(this, host === hostname ? "127.0.0.1" : host, ...args);
  };
  syncBuiltinESMExports();
}
`;
}

export function previewTestNodeOptions(
  appPath: string,
  existing = process.env.NODE_OPTIONS,
): string {
  // NODE_OPTIONS is parsed by Node, not a shell. Forward slashes avoid Windows
  // backslash escaping; JSON quoting preserves spaces and embedded quotes.
  const preloadPath = path.join(appPath, PREVIEW_DNS_RELATIVE_PATH);
  const preload =
    process.platform === "win32"
      ? preloadPath.replaceAll("\\", "/")
      : preloadPath;
  return `${existing ?? ""} --require ${JSON.stringify(preload)}`.trim();
}
