[project]
name = "dyad-git"
version = "0.1.7"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Will Chen", email = "willchen90@gmail.com" }]
requires-python = ">=3.10"
dependencies = ["gitpython>=3.1.44"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
