import { DyadError, DyadErrorKind, isDyadError } from "@/errors/dyad_error";
import { IS_TEST_BUILD } from "@/ipc/utils/test_utils";
import { retryWithRateLimit } from "@/ipc/utils/retryWithRateLimit";
import { renderTestDatabaseSchema } from "@/lib/test_database_schema";
import {
  getProjectApiKeys,
  getSupabaseClient,
  type SupabaseApiKey,
} from "./supabase_management_client";
import {
  SUPABASE_SCHEMA_QUERY,
  SUPABASE_FUNCTIONS_QUERY,
} from "./supabase_schema_query";
import {
  buildSchemaSnapshotSql,
  filterSchemaForTable,
  getSchemaFromSnapshot,
  missingPublicTableComment,
  renderSchemaSql,
} from "ts-pg-schema-diff";

// Prefix of a new-format publishable key.
const PUBLISHABLE_KEY_PREFIX = "sb_publishable_";

/**
 * Pick the key the generated app authenticates with, newest format first.
 *
 * Deliberately NOT one `find` with an OR across the formats: Supabase doesn't
 * document the ordering of `/api-keys`, and it keeps listing the legacy
 * `anon`/`service_role` pair after they've been disabled in the dashboard. A
 * predicate that treats a legacy key as an equal alternative therefore lets a
 * DISABLED key win on position — and the app then 401s with "Legacy API keys
 * are disabled" on every request it makes, including sign-in. The legacy tier
 * stays last so projects that never migrated keep working.
 */
function pickPublishableKey(
  keys: readonly SupabaseApiKey[],
): SupabaseApiKey | undefined {
  return (
    keys.find(
      (key) =>
        key.type === "publishable" &&
        key.api_key?.startsWith(PUBLISHABLE_KEY_PREFIX),
    ) ??
    keys.find((key) => key.type === "publishable") ??
    keys.find((key) => key.name === "anon")
  );
}

export async function getPublishableKey({
  projectId,
  organizationSlug,
}: {
  projectId: string;
  organizationSlug: string | null;
}) {
  if (IS_TEST_BUILD) {
    return "test-publishable-key";
  }

  let keys;
  try {
    // No reveal: publishable keys are public by design and never redacted, and
    // revealing would expose the project's secret keys for nothing.
    keys = await getProjectApiKeys({ projectId, organizationSlug });
  } catch (error) {
    // getProjectApiKeys acquires the Management client itself, so an expired
    // Supabase login arrives here as a DyadErrorKind.Auth. Re-wrapping it as
    // External would drop the classification that drives the re-auth prompt.
    if (isDyadError(error)) {
      throw error;
    }
    throw new DyadError(
      `Failed to fetch API keys for Supabase project "${projectId}". This could be due to: 1) Invalid project ID, 2) Network connectivity issues, or 3) Supabase API unavailability. Original error: ${error instanceof Error ? error.message : String(error)}`,
      DyadErrorKind.External,
    );
  }
  if (!keys?.length) {
    throw new DyadError(
      "No keys found for Supabase project " + projectId,
      DyadErrorKind.NotFound,
    );
  }
  const publishableKey = pickPublishableKey(keys);

  // Checks the VALUE, not just the entry: the lower tiers match on `type`/`name`
  // alone, so a key listed without its value would otherwise be baked into the
  // generated client as `undefined`.
  if (!publishableKey?.api_key) {
    throw new DyadError(
      "Dyad couldn't find a publishable key for this Supabase project. It may be paused or connected through the wrong Supabase account. Resume the project in Supabase, or reconnect the correct project in Dyad. See https://dyad.sh/docs/integrations/supabase#no-publishable-keys",
      DyadErrorKind.NotFound,
    );
  }
  return publishableKey.api_key;
}
export const getSupabaseClientCode = async function ({
  projectId,
  organizationSlug,
}: {
  projectId: string;
  organizationSlug: string | null;
}) {
  const publishableKey = await getPublishableKey({
    projectId,
    organizationSlug,
  });
  return `
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://${projectId}.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "${publishableKey}";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);`;
};

export async function getSupabaseContext({
  supabaseProjectId,
  organizationSlug,
}: {
  supabaseProjectId: string;
  organizationSlug: string | null;
}) {
  if (IS_TEST_BUILD) {
    if (supabaseProjectId === "test-branch-project-id") {
      return "1234".repeat(200_000);
    }
    return "[[TEST_BUILD_SUPABASE_CONTEXT]]";
  }

  const supabase = await getSupabaseClient({ organizationSlug });
  const publishableKey = await getPublishableKey({
    projectId: supabaseProjectId,
    organizationSlug,
  });
  const schema = await retryWithRateLimit(
    () => supabase.runQuery(supabaseProjectId, SUPABASE_SCHEMA_QUERY),
    `Get schema for ${supabaseProjectId}`,
  );

  const secrets = await retryWithRateLimit(
    () => supabase.getSecrets(supabaseProjectId),
    `Get secrets for ${supabaseProjectId}`,
  );
  const secretNames = secrets?.map((secret) => secret.name);

  // TODO: include EDGE FUNCTIONS and SECRETS!

  const context = `
  # Supabase Context

  ## Supabase Project ID
  ${supabaseProjectId}

  ## Publishable key (aka anon key)
  ${publishableKey}

  ## Secret names (environmental variables)
  ${JSON.stringify(secretNames)}

  ## Schema
  ${JSON.stringify(schema)}
  `;

  return context;
}

// Query to get just table names (lightweight)
const TABLE_NAMES_QUERY = `
  SELECT table_name 
  FROM information_schema.tables 
  WHERE table_schema = 'public'
  ORDER BY table_name;
`;

function normalizeRunQueryRows(
  result: unknown,
): readonly Record<string, unknown>[] {
  if (Array.isArray(result)) {
    return result as readonly Record<string, unknown>[];
  }
  if (result && typeof result === "object") {
    const maybeRows = (result as { data?: unknown; result?: unknown }).data;
    if (Array.isArray(maybeRows)) {
      return maybeRows as readonly Record<string, unknown>[];
    }
    const maybeResultRows = (result as { result?: unknown }).result;
    if (Array.isArray(maybeResultRows)) {
      return maybeResultRows as readonly Record<string, unknown>[];
    }
  }
  const shape =
    result !== null && typeof result === "object"
      ? `object keys: ${Object.keys(result).join(", ") || "none"}`
      : typeof result;
  throw new Error(`Unexpected Supabase runQuery response shape (${shape})`);
}

/**
 * Get high-level Supabase project info: project ID, publishable key, secret names, and table names.
 * This is a lightweight call that doesn't fetch full schema details.
 * Optionally includes database functions when include_db_functions is true.
 */
export async function getSupabaseProjectInfo({
  supabaseProjectId,
  organizationSlug,
  includeDbFunctions,
}: {
  supabaseProjectId: string;
  organizationSlug: string | null;
  includeDbFunctions?: boolean;
}): Promise<string> {
  if (IS_TEST_BUILD) {
    let result = `# Supabase Project Info

## Project ID
${supabaseProjectId}

## Publishable Key
test-publishable-key

## Secret Names
["TEST_SECRET_1", "TEST_SECRET_2"]

## Table Names
["users", "posts", "comments"]
`;
    if (includeDbFunctions) {
      result += `
## Database Functions
[{"name": "test_function", "arguments": "", "return_type": "void", "language": "plpgsql"}]
`;
    }
    return result;
  }

  const supabase = await getSupabaseClient({ organizationSlug });
  const publishableKey = await getPublishableKey({
    projectId: supabaseProjectId,
    organizationSlug,
  });

  const secrets = await retryWithRateLimit(
    () => supabase.getSecrets(supabaseProjectId),
    `Get secrets for ${supabaseProjectId}`,
  );
  const secretNames = secrets?.map((secret) => secret.name) ?? [];

  const tableResult = await retryWithRateLimit(
    () => supabase.runQuery(supabaseProjectId, TABLE_NAMES_QUERY),
    `Get table names for ${supabaseProjectId}`,
  );
  const tableNames =
    (tableResult as unknown as { table_name: string }[] | undefined)?.map(
      (row) => row.table_name,
    ) ?? [];

  let result = `# Supabase Project Info

## Project ID
${supabaseProjectId}

## Publishable Key
${publishableKey}

## Secret Names
${JSON.stringify(secretNames)}

## Table Names
${JSON.stringify(tableNames)}
`;

  if (includeDbFunctions) {
    const functionsResult = await retryWithRateLimit(
      () => supabase.runQuery(supabaseProjectId, SUPABASE_FUNCTIONS_QUERY),
      `Get DB functions for ${supabaseProjectId}`,
    );
    result += `
## Database Functions
${JSON.stringify(functionsResult)}
`;
  }

  return result;
}

/**
 * Get database table schema. If tableName is provided, returns schema for that specific table.
 * If tableName is omitted, returns schema for all tables.
 */
export async function getSupabaseTableSchema({
  supabaseProjectId,
  organizationSlug,
  tableName,
}: {
  supabaseProjectId: string;
  organizationSlug: string | null;
  tableName?: string;
}): Promise<string> {
  if (IS_TEST_BUILD) {
    return renderTestDatabaseSchema(tableName);
  }

  try {
    const supabase = await getSupabaseClient({ organizationSlug });
    const snapshotResult = await retryWithRateLimit(
      () =>
        supabase.runQuery(
          supabaseProjectId,
          buildSchemaSnapshotSql({
            includeSchemas: ["public"],
            tableName,
          }),
        ),
      `Get schema snapshot for ${supabaseProjectId}`,
    );
    const snapshotRows = normalizeRunQueryRows(snapshotResult);
    if (snapshotRows.length === 0) {
      throw new Error("Supabase schema snapshot query returned no rows");
    }
    const snapshot = snapshotRows[0]?.schema_snapshot;
    if (snapshot === undefined) {
      throw new Error(
        "Supabase schema snapshot response is missing schema_snapshot",
      );
    }
    const schema = await getSchemaFromSnapshot(snapshot);
    if (!tableName && schema.tables.length === 0) {
      return "-- No public tables found.";
    }
    const filteredSchema = tableName
      ? filterSchemaForTable(schema, { tableName })
      : schema;
    return renderSchemaSql(filteredSchema, {
      emptySchemaComment: tableName
        ? missingPublicTableComment(tableName)
        : "-- No public tables found.",
    });
  } catch (error) {
    if (isDyadError(error)) {
      throw error;
    }
    throw new DyadError(
      `Failed to get table schema for Supabase project "${supabaseProjectId}": ${error instanceof Error ? error.message : String(error)}`,
      DyadErrorKind.External,
    );
  }
}
