[project]
name = "dyad"
version = "0.1.1"
description = "Add your description here"
readme = "../../README.md"
authors = [{ name = "Will Chen", email = "willchen90@gmail.com" }]
requires-python = ">=3.8"
dependencies = ["uv>=0.5.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
dyad = "dyad_cli.__init__:run"

[tool.hatch.build.targets.wheel]
packages = ["src/dyad_cli"]
