// System prompt based on https://github.com/jjleng/code-panda/blob/61f1fa514c647de1a8d2ad7f85102d49c6db2086/cp-agent/cp_agent/kb/data/supabase/login.txt
// which is Apache 2.0 licensed and copyrighted to Jijun Leng
// https://github.com/jjleng/code-panda/blob/61f1fa514c647de1a8d2ad7f85102d49c6db2086/LICENSE

export const SUPABASE_NO_MANUAL_MIGRATIONS_RULE =
  "- **No manual migrations:** Always use the execute SQL tool to run SQL queries against the Supabase database. NEVER write SQL migration files to `supabase/migrations/` — those files are automatically generated by an external system and must not be created or modified manually.";
export const SUPABASE_GRANTS_AND_RLS_RULE =
  "- **Grants and RLS are separate security layers:** `GRANT` controls whether a Postgres role (`anon`, `authenticated`, or `service_role`) can access a table through the Data API at all; RLS policies control which rows the role can read or modify after the table is accessible.";
export const SUPABASE_IMPLEMENTER_NO_MANUAL_MIGRATIONS_RULE =
  "- **No manual migrations:** Never create or edit files under `supabase/migrations/`. Report required schema or SQL changes to the root Agent for execution.";
export const SUPABASE_IMPLEMENTER_RLS_RULE =
  "- **RLS is mandatory:** Enable RLS for every table exposed through Supabase and require appropriate policies for each operation the app uses (SELECT, INSERT, UPDATE, and DELETE); never propose grants to `anon` or `authenticated` without proper RLS policies.";
export const SUPABASE_ROOT_RLS_RULE =
  "- **RLS is mandatory:** Enable RLS for every table exposed through Supabase and require appropriate policies for each operation the app uses (SELECT, INSERT, UPDATE, and DELETE); never grant `anon` or `authenticated` access without proper RLS policies.";
export const SUPABASE_ROOT_NO_MANUAL_MIGRATIONS_RULE =
  "- **No manual migrations:** Never create or edit files under `supabase/migrations/`; reconnect the linked Supabase organization before attempting schema changes.";
export const SUPABASE_SERVICE_ROLE_BROWSER_RULE =
  "- **Keep the service role server-side:** The service role is for trusted server-side code only and MUST NEVER be used in browser/client code.";
export const SUPABASE_EDGE_FUNCTION_JWT_RULE =
  "- **Verify Edge Function JWTs:** Supabase Edge Functions deploy with `verify_jwt: false`. For authenticated or privileged operations, explicitly verify and decode the caller's JWT in function code; checking only that an Authorization header exists is not authentication.";
export const SUPABASE_DISCONNECTED_SYSTEM_PROMPT = `
This app is already linked to a Supabase project, but credentials for its Supabase organization are unavailable. Do not offer to add another database integration. Tell the user to reconnect the linked Supabase organization before attempting provider operations.

Continue to preserve these Supabase code-safety invariants while disconnected:
${SUPABASE_SERVICE_ROLE_BROWSER_RULE}
${SUPABASE_EDGE_FUNCTION_JWT_RULE}
${SUPABASE_GRANTS_AND_RLS_RULE}
${SUPABASE_ROOT_RLS_RULE}
${SUPABASE_ROOT_NO_MANUAL_MIGRATIONS_RULE}`;

export function getSupabaseAvailableSystemPrompt(supabaseClientCode: string) {
  return `
# Supabase Instructions

The user has Supabase available for their app so use it for any auth, database or server-side functions.

## Supabase Client Setup

Check if a Supabase client exists at \`src/integrations/supabase/client.ts\`.

**If it doesn't exist**, do both of the following:

1. **Create the client file** at \`src/integrations/supabase/client.ts\` (or the most appropriate path for the project structure) with this code:
\`\`\`typescript
${supabaseClientCode}
\`\`\`

2. **Add the dependency** \`@supabase/supabase-js\` to the project.

## Auth

When asked to add authentication or login feature to the app, always follow these steps:

1. User Profile Assessment:
   - Confirm if user profile data storage is needed (username, roles, avatars)
   - If yes: Create profiles table using the execute SQL tool
   - If no: Proceed with basic auth setup

2. Core Authentication Setup:
   a. UI Components:
      - Use @supabase/auth-ui-react Auth component
      - Apply light theme (unless dark theme exists)
      - Style to match application design
      - Skip third-party providers unless specified

   b. Session Management:
      - Wrap app with SessionContextProvider (create this yourself)
      - Import supabase client from @/lib/supabaseClient
      - Implement auth state monitoring using supabase.auth.onAuthStateChange
      - Add automatic redirects:
        - Authenticated users → main page
        - Unauthenticated users → login page

   c. Error Handling:
      - Implement AuthApiError handling utility
      - Monitor auth state changes for errors
      - Clear errors on sign-out
      - DO NOT use onError prop (unsupported)

IMPORTANT! You cannot skip step 1.

Below code snippets are provided for reference:

Login state management:

useEffect(() => {
  const { data } = supabase.auth.onAuthStateChange((event, session) => {
    if (event === 'INITIAL_SESSION') {
      // handle initial session
    } else if (event === 'SIGNED_IN') {
      // handle sign in event
    } else if (event === 'SIGNED_OUT') {
      // handle sign out event
    } else if (event === 'PASSWORD_RECOVERY') {
      // handle password recovery event
    } else if (event === 'TOKEN_REFRESHED') {
      // handle token refreshed event
    } else if (event === 'USER_UPDATED') {
      // handle user updated event
    }
  })

  // call unsubscribe to remove the callback
  return () => data.subscription.unsubscribe();
}, []);


Login page (NOTE: THIS FILE DOES NOT EXIST. YOU MUST GENERATE IT YOURSELF.):

**File: \`src/pages/Login.tsx\`**
\`\`\`tsx
import { Auth } from '@supabase/auth-ui-react';
import { ThemeSupa } from '@supabase/auth-ui-shared';
function Login() {
  // Other code here
  return (
    <Auth
      supabaseClient={supabase}
      providers={[]}
      appearance={{
        theme: ThemeSupa,
      }}
      theme="light"
    />
  );
}
\`\`\`


## Database

${SUPABASE_NO_MANUAL_MIGRATIONS_RULE}

You will need to setup the database schema using the execute SQL tool.

### Data API Grants

Supabase Data API access requires explicit Postgres grants. This applies to Supabase's REST API, GraphQL API, and \`supabase-js\`.

${SUPABASE_GRANTS_AND_RLS_RULE}

- If grants are missing, requests can fail with \`permission denied for table ...\` before RLS policies are evaluated.

When creating a \`public\` application table intended for Supabase API access, ALWAYS include explicit grants in the same SQL batch as table creation, RLS, and policies.

#### Required Grant Patterns:

1. **Server-side Supabase API access:**
   - For normal application tables, ALWAYS grant full access to \`service_role\`.
   ${SUPABASE_SERVICE_ROLE_BROWSER_RULE}

\`\`\`sql
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.table_name TO service_role;
\`\`\`

2. **Authenticated client access:**
   - Grant only the operations the authenticated client needs.
   - If users need full CRUD through \`supabase-js\`, grant full CRUD to \`authenticated\`.

\`\`\`sql
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.table_name TO authenticated;
\`\`\`

3. **Public unauthenticated access:**
   - Only grant \`anon\` access when public unauthenticated access is specifically required.
   - Most app tables should NOT grant anything to \`anon\`.

\`\`\`sql
-- ONLY if public read access is specifically required
GRANT SELECT ON TABLE public.table_name TO anon;
\`\`\`

4. **Sequence-backed inserts:**
   - If a table uses \`SERIAL\`, identity columns, or explicit sequences, also grant sequence privileges to roles that insert rows.
   - Skip sequence grants when using UUID primary keys such as \`gen_random_uuid()\`.

\`\`\`sql
GRANT USAGE, SELECT ON SEQUENCE public.table_name_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.table_name_id_seq TO service_role;
\`\`\`

### Row Level Security (RLS)

**⚠️ SECURITY WARNING: ALWAYS ENABLE RLS ON ALL TABLES**

Row Level Security (RLS) is MANDATORY for all tables exposed through Supabase. If a table is granted to \`anon\` or \`authenticated\` without proper RLS policies, users can read, insert, update, or delete data they should not access, creating massive security vulnerabilities.

#### RLS Best Practices (REQUIRED):

1. **Enable RLS on Every Table:**
\`\`\`sql
ALTER TABLE table_name ENABLE ROW LEVEL SECURITY;
\`\`\`

2. **Create Appropriate Policies for Each Operation:**
   - SELECT policies (who can read data)
   - INSERT policies (who can create data)
   - UPDATE policies (who can modify data)
   - DELETE policies (who can remove data)

3. **Common RLS Policy Patterns:**

   **Public Read Access:** (ONLY USE THIS IF SPECIFICALLY REQUESTED)
\`\`\`sql
CREATE POLICY "Public read access" ON table_name FOR SELECT USING (true);
\`\`\`

   **User-specific Data Access:**
\`\`\`sql
CREATE POLICY "Users can only see their own data" ON table_name
FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Users can only insert their own data" ON table_name
FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can only update their own data" ON table_name
FOR UPDATE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Users can only delete their own data" ON table_name
FOR DELETE TO authenticated USING (auth.uid() = user_id);
\`\`\`

#### RLS Policy Creation Template:

When creating any table, ALWAYS follow this pattern:

\`\`\`sql
-- Create table
CREATE TABLE public.table_name (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  -- other columns
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Data API Grants (REQUIRED)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.table_name TO service_role;
-- Grant only the operations the authenticated client actually needs
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.table_name TO authenticated;
-- ONLY if public unauthenticated read access is specifically required
-- GRANT SELECT ON TABLE public.table_name TO anon;

-- Enable RLS (REQUIRED)
ALTER TABLE public.table_name ENABLE ROW LEVEL SECURITY;

-- Create policies for each operation needed
CREATE POLICY "policy_name_select" ON public.table_name
FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "policy_name_insert" ON public.table_name
FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "policy_name_update" ON public.table_name
FOR UPDATE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "policy_name_delete" ON public.table_name
FOR DELETE TO authenticated USING (auth.uid() = user_id);
\`\`\`

**REMINDER: If you grant client API access to a table without proper RLS policies, users can access, modify, or delete data they should not access.**

#### Security Checklist for Every Database Operation:

Before creating any table or database schema, verify:

- ✅ RLS is enabled on the table
- ✅ Explicit Data API grants are added for each intended API role
- ✅ \`service_role\` has full access for normal application tables
- ✅ \`anon\` grants are avoided unless public unauthenticated access is specifically required
- ✅ Sequence grants are included only when sequence-backed inserts are used
- ✅ Appropriate SELECT policies are defined
- ✅ Appropriate INSERT policies are defined
- ✅ Appropriate UPDATE policies are defined  
- ✅ Appropriate DELETE policies are defined
- ✅ Policies follow the principle of least privilege
- ✅ User can only access their own data (unless public access is specifically required)
- ✅ All user-specific policies include \`TO authenticated\` for additional security

**Remember: Without proper RLS policies, your database is exposed to unauthorized access.**

## Creating User Profiles

If the user wants to create a user profile, use the following code:

### Create profiles table in public schema with proper RLS

\`\`\`sql
-- Create profiles table
CREATE TABLE public.profiles (
  id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name TEXT,
  last_name TEXT,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (id)
);

-- Grant Data API access
GRANT SELECT, UPDATE ON TABLE public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.profiles TO service_role;

-- Enable RLS (REQUIRED for security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create secure policies for each operation
CREATE POLICY "profiles_select_policy" ON public.profiles
FOR SELECT TO authenticated USING (auth.uid() = id);

CREATE POLICY "profiles_insert_policy" ON public.profiles
FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

CREATE POLICY "profiles_update_policy" ON public.profiles
FOR UPDATE TO authenticated USING (auth.uid() = id);

CREATE POLICY "profiles_delete_policy" ON public.profiles
FOR DELETE TO authenticated USING (auth.uid() = id);
\`\`\`

**SECURITY NOTE:** These policies ensure users can only access, modify, and delete their own profile data. If you need public profile visibility (e.g., for a social app), add an additional public read policy only if specifically required:

\`\`\`sql
-- ONLY add this policy if public profile viewing is specifically required
GRANT SELECT ON TABLE public.profiles TO anon;

CREATE POLICY "profiles_public_read_policy" ON public.profiles
FOR SELECT USING (true);
\`\`\`

**IMPORTANT:** For security, Auth schema isn't exposed in the API. Create user tables in public schema to access user data via API.

**CAUTION:** Only use primary keys as foreign key references for Supabase-managed schemas like auth.users. While PostgreSQL allows referencing columns backed by unique indexes, primary keys are guaranteed not to change.

## Auto-Update Profiles on Signup

### Function to insert profile when user signs up

\`\`\`sql
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, first_name, last_name)
  VALUES (
    new.id,
    new.raw_user_meta_data ->> 'first_name',
    new.raw_user_meta_data ->> 'last_name'
  );
  RETURN new;
END;
$$;

-- Trigger the function on user creation
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
\`\`\`

## Server-side Edge Functions

### When to Use Edge Functions

- Use edge functions for:
  - API-to-API communications
  - Handling sensitive API tokens or secrets
  - Typical backend work requiring server-side logic

### Key Implementation Principles

1. Location:
- Write functions in the supabase/functions folder
- Each function should be in a standalone directory where the main file is index.ts (e.g., supabase/functions/hello/index.ts)
- Reusable utilities belong in the supabase/functions/_shared folder. Import them in your edge functions with relative paths like ../_shared/logger.ts.
- Edge Functions are deployed automatically after edits, either immediately or during end-of-turn finalization.
- Do NOT tell the user to manually deploy the edge function using the CLI or Supabase Console. It's unhelpful and not needed.

2. Configuration:
- DO NOT edit config.toml

3. Supabase Client:
- Do not import code from supabase/
- Functions operate in their own context

4. Function Invocation:
- Use supabase.functions.invoke() method
- Avoid raw HTTP requests like fetch or axios

5. CORS Configuration:
- Always include CORS headers:

\`\`\`
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type'
};
\`\`\`

- Implement OPTIONS request handler:

\`\`\`
if (req.method === 'OPTIONS') {
  return new Response(null, { headers: corsHeaders });
}
\`\`\`

6. Authentication:
${SUPABASE_EDGE_FUNCTION_JWT_RULE}
- Example authentication handling:

\`\`\`
const authHeader = req.headers.get('Authorization')
if (!authHeader) {
  return new Response('Unauthorized', { status: 401, headers: corsHeaders })
}

const token = authHeader.replace('Bearer ', '')
// Manually verify the JWT token using your preferred method
// e.g., using jose library or Supabase library method \`supabase.auth.getClaims()\`
\`\`\`

7. Function Design:
- Include all core application logic within the edge function
- Do not import code from other project files

8. Secrets Management:
- Pre-configured secrets, no need to set up manually:
  - SUPABASE_URL
  - SUPABASE_ANON_KEY
  - SUPABASE_SERVICE_ROLE_KEY
  - SUPABASE_DB_URL

- For new secrets/API tokens:
  - Inform user to set up via Supabase Console
  - Direct them to: Project -> Edge Functions -> Manage Secrets
  - Use <resource-link> for guidance

9. Logging:
- Implement comprehensive logging for debugging purposes. 

  CRITICAL LOGGING RULE:
  - Every log statement MUST start with "[function-name]".
  - This applies to ALL console methods: console.log, console.error, console.warn, console.debug, console.info.
  - Do NOT add any console statements that do not follow this format under any circumstances.

  Examples:
  - Example: console.log("[function-name] message", { data });
  - Example: console.error("[function-name] error message", { error });

10. Linking:
Use <resource-link> to link to the relevant edge function

11. Client Invocation:
   - Call edge functions using the full hardcoded URL path
   - Format: https://SUPABASE_PROJECT_ID.supabase.co/functions/v1/EDGE_FUNCTION_NAME
   - Note: Environment variables are not supported - always use full hardcoded URLs

12. Edge Function Template:

**File: \`supabase/functions/hello/index.ts\`**
\`\`\`typescript
import { serve } from "https://deno.land/std@0.190.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  // Manual authentication handling (since verify_jwt is false)
  const authHeader = req.headers.get('Authorization')
  if (!authHeader) {
    return new Response('Unauthorized', {
      status: 401,
      headers: corsHeaders
    })
  }

  // ... function logic
})
\`\`\`
`;
}

export const SUPABASE_NOT_AVAILABLE_SYSTEM_PROMPT = `
If the user wants to use supabase or do something that requires auth, database or server-side functions (e.g. loading API keys, secrets),
tell them that they need to add a database to their app.

The following response will show a prompt that allows the user to choose and set up a database provider.

<dyad-add-integration></dyad-add-integration>

# Examples

## Example 1: User wants to use a database

### User prompt

I want to use a database in my app.

### Assistant response

You need to first add a database to your app.

<dyad-add-integration></dyad-add-integration>

## Example 2: User wants to add auth to their app

### User prompt

I want to add auth to my app.

### Assistant response

You need to first add a database to your app and then we can add auth.

<dyad-add-integration></dyad-add-integration>
`;
